// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB35kqJ0J7uXIdGHlwmayPszscHugdzNeo',
    appId: '1:740176827982:web:c4b7c9d4e9df19dc18951f',
    messagingSenderId: '740176827982',
    projectId: 'gds-pro-9159b',
    authDomain: 'gds-pro-9159b.firebaseapp.com',
    storageBucket: 'gds-pro-9159b.appspot.com',
    measurementId: 'G-3LTZY0YQ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4T52Gt5npLPkCcsBJD9vhn9eBZvPYeUI',
    appId: '1:740176827982:android:a3f8365862688e0318951f',
    messagingSenderId: '740176827982',
    projectId: 'gds-pro-9159b',
    storageBucket: 'gds-pro-9159b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPINzhpbCFobKzDSCek_19UjxJLVGkfNg',
    appId: '1:740176827982:ios:86f4c69431edacbc18951f',
    messagingSenderId: '740176827982',
    projectId: 'gds-pro-9159b',
    storageBucket: 'gds-pro-9159b.appspot.com',
    iosClientId: '740176827982-drra7td4uq9r313uvg41nocovh65nn23.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionDeStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPINzhpbCFobKzDSCek_19UjxJLVGkfNg',
    appId: '1:740176827982:ios:86f4c69431edacbc18951f',
    messagingSenderId: '740176827982',
    projectId: 'gds-pro-9159b',
    storageBucket: 'gds-pro-9159b.appspot.com',
    iosClientId: '740176827982-drra7td4uq9r313uvg41nocovh65nn23.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionDeStock',
  );
}
